"""Add officer names and signing times

Revision ID: 1377065ccd9a
Revises: b306ce1a9844
Create Date: 2026-08-24 15:38:48.755606

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1377065ccd9a'
down_revision = 'b306ce1a9844'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_receipt_is_deleted'), ['is_deleted'], unique=False)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reception_officer_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('reception_signed_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('library_officer_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('library_signed_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('admissions_officer_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('admissions_signed_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('accounts_officer_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('accounts_signed_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('systems_officer_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('systems_signed_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('adosa_officer_name', sa.String(length=150), nullable=True))
        batch_op.add_column(sa.Column('adosa_signed_time', sa.DateTime(), nullable=True))

    with op.batch_alter_table('system_notifications', schema=None) as batch_op:
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_notifications', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('adosa_signed_time')
        batch_op.drop_column('adosa_officer_name')
        batch_op.drop_column('systems_signed_time')
        batch_op.drop_column('systems_officer_name')
        batch_op.drop_column('accounts_signed_time')
        batch_op.drop_column('accounts_officer_name')
        batch_op.drop_column('admissions_signed_time')
        batch_op.drop_column('admissions_officer_name')
        batch_op.drop_column('library_signed_time')
        batch_op.drop_column('library_officer_name')
        batch_op.drop_column('reception_signed_time')
        batch_op.drop_column('reception_officer_name')

    with op.batch_alter_table('receipt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_receipt_is_deleted'))

    # ### end Alembic commands ###
