"""Added clearance fields

Revision ID: 1b3087ef9f69
Revises: 
Create Date: 2026-07-10 19:13:53.061681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b3087ef9f69'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clearance_number', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('verification_code', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('pdf_generated_date', sa.DateTime(), nullable=True))
        batch_op.create_unique_constraint("uq_student_verification_code",["verification_code"])
        batch_op.create_unique_constraint("uq_student_clearance_number",["clearance_number"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('pdf_generated_date')
        batch_op.drop_column('verification_code')
        batch_op.drop_column('clearance_number')

    # ### end Alembic commands ###
