"""Add school column to student

Revision ID: 3127dc0ab19e
Revises: 4f56748cb3b5
Create Date: 2026-08-30 21:38:35.549887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3127dc0ab19e'
down_revision = '4f56748cb3b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('school', sa.String(length=100), nullable=True))
        batch_op.alter_column('semester1_payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Pending'"))
        batch_op.alter_column('semester2_payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'Pending'"))
        batch_op.create_index(batch_op.f('ix_student_school'), ['school'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_school'))
        batch_op.alter_column('semester2_payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Pending'"))
        batch_op.alter_column('semester1_payment_status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'Pending'"))
        batch_op.drop_column('school')

    # ### end Alembic commands ###
