"""Add Health Sciences semester payment fields

Revision ID: 4f56748cb3b5
Revises: b3cece2db08b
Create Date: 2026-08-29 02:04:18.691549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f56748cb3b5'
down_revision = 'b3cece2db08b'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'semester1_amount',
                sa.Float(),
                nullable=False,
                server_default=sa.text('0')
            )
        )
        batch_op.add_column(
            sa.Column(
                'semester1_payment_date',
                sa.DateTime(),
                nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                'semester1_payment_status',
                sa.String(length=20),
                nullable=False,
                server_default=sa.text("'Pending'")
            )
        )
        batch_op.add_column(
            sa.Column(
                'semester2_amount',
                sa.Float(),
                nullable=False,
                server_default=sa.text('0')
            )
        )
        batch_op.add_column(
            sa.Column(
                'semester2_payment_date',
                sa.DateTime(),
                nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                'semester2_payment_status',
                sa.String(length=20),
                nullable=False,
                server_default=sa.text("'Pending'")
            )
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('semester2_payment_status')
        batch_op.drop_column('semester2_payment_date')
        batch_op.drop_column('semester2_amount')
        batch_op.drop_column('semester1_payment_status')
        batch_op.drop_column('semester1_payment_date')
        batch_op.drop_column('semester1_amount')

    # ### end Alembic commands ###
