"""Add student_email to ReceiptNotification

Revision ID: 50e1dab2fc80
Revises: ba2b68137a93
Create Date: 2026-08-08 22:01:15.517403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50e1dab2fc80'
down_revision = 'ba2b68137a93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receipt_notifications', schema=None) as batch_op:
        batch_op.drop_column('student_email')

    # ### end Alembic commands ###
