"""Added electronic signatures

Revision ID: 96c7780c4371
Revises: 1b3087ef9f69
Create Date: 2026-08-04 19:03:52.462250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96c7780c4371'
down_revision = '1b3087ef9f69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accounts_signature', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('library_signature', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('systems_signature', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('admissions_signature', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('reception_signature', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('adosa_signature', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('executive_signature', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('executive_signature')
        batch_op.drop_column('adosa_signature')
        batch_op.drop_column('reception_signature')
        batch_op.drop_column('admissions_signature')
        batch_op.drop_column('systems_signature')
        batch_op.drop_column('library_signature')
        batch_op.drop_column('accounts_signature')

    # ### end Alembic commands ###
