"""Add student_email to SystemNotification

Revision ID: b306ce1a9844
Revises: 50e1dab2fc80
Create Date: 2026-08-08 23:10:32.157460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b306ce1a9844'
down_revision = '50e1dab2fc80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_notifications', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_email', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('system_notifications', schema=None) as batch_op:
        batch_op.drop_column('student_email')

    # ### end Alembic commands ###
